// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const ingestALPR = `-- name: IngestALPR :one
select public.ingest_alpr($1::jsonb) as result
`

func (q *Queries) IngestALPR(ctx context.Context, doc []byte) (string, error) {
	row := q.db.QueryRow(ctx, ingestALPR, doc)
	var result string
	err := row.Scan(&result)
	return result, err
}
