// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID                 int64
	PlateID            int64
	HotlistID          int64
	CreatedAt          pgtype.Timestamptz
	Status             interface{}
	Attempts           int32
	LastError          pgtype.Text
	LockedAt           pgtype.Timestamptz
	LockedBy           pgtype.Text
	ProcessingDeadline pgtype.Timestamptz
	VisibleAt          pgtype.Timestamptz
}

type Alpr struct {
	ID         int64
	Doc        []byte
	InsertedAt pgtype.Timestamp
	PlateNum   pgtype.Text
	// the time that the alpr system read the plate from a camera
	ReadTime   pgtype.Timestamp
	CameraName pgtype.Text
	PlateCode  pgtype.Text
	// used to build url to direct image access from S3
	ImageID  pgtype.Text
	Location interface{}
	// unique id of the read scan
	ReadID pgtype.Text
	Make   pgtype.Text
	// sedan, suv, etc
	VehicleType pgtype.Text
	Color       pgtype.Text
}

type AlprDeadletter struct {
	ID       int64
	FailedAt pgtype.Timestamptz
	Stage    string
	Sqlstate pgtype.Text
	Message  pgtype.Text
	Detail   pgtype.Text
	Hint     pgtype.Text
	Context  pgtype.Text
	Doc      []byte
}

type AlprIngest struct {
	ID          int64
	Doc         []byte
	PlateNum    pgtype.Text
	ReadTime    pgtype.Timestamptz
	CameraName  pgtype.Text
	PlateCode   pgtype.Text
	ImageID     pgtype.Text
	Location    interface{}
	ReadID      pgtype.Text
	Make        pgtype.Text
	VehicleType pgtype.Text
	Color       pgtype.Text
	InsertedAt  pgtype.Timestamptz
}

type Hotlist struct {
	ID                    int64
	HotlistID             string
	Status                string
	StartDate             pgtype.Timestamptz
	ExpirationDate        pgtype.Timestamptz
	ReasonType            pgtype.Text
	PlateNumber           string
	NjsnapHitNotification pgtype.Bool
	Doc                   []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type HotlistAlertEvent struct {
	ID        int64
	Kind      string
	CreatedAt pgtype.Timestamptz
	Details   []byte
}

type HotlistAlertState struct {
	ID                   int32
	Mode                 interface{}
	PhaseAttempts        int32
	FirstFailedAt        pgtype.Timestamptz
	VendorDownNotifiedAt pgtype.Timestamptz
	NextDueAt            pgtype.Timestamptz
}
